# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datamsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datamsg.proto',
  package='mqdemo',
  syntax='proto3',
  serialized_pb=_b('\n\rdatamsg.proto\x12\x06mqdemo\"\'\n\tReqAction\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\tReqResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQACTION = _descriptor.Descriptor(
  name='ReqAction',
  full_name='mqdemo.ReqAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mqdemo.ReqAction.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='mqdemo.ReqAction.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=64,
)


_REQRESULT = _descriptor.Descriptor(
  name='ReqResult',
  full_name='mqdemo.ReqResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mqdemo.ReqResult.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='mqdemo.ReqResult.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ReqAction'] = _REQACTION
DESCRIPTOR.message_types_by_name['ReqResult'] = _REQRESULT

ReqAction = _reflection.GeneratedProtocolMessageType('ReqAction', (_message.Message,), dict(
  DESCRIPTOR = _REQACTION,
  __module__ = 'datamsg_pb2'
  # @@protoc_insertion_point(class_scope:mqdemo.ReqAction)
  ))
_sym_db.RegisterMessage(ReqAction)

ReqResult = _reflection.GeneratedProtocolMessageType('ReqResult', (_message.Message,), dict(
  DESCRIPTOR = _REQRESULT,
  __module__ = 'datamsg_pb2'
  # @@protoc_insertion_point(class_scope:mqdemo.ReqResult)
  ))
_sym_db.RegisterMessage(ReqResult)


# @@protoc_insertion_point(module_scope)
