// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datamsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "datamsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mqdemo {

namespace {

const ::google::protobuf::Descriptor* ReqAction_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReqAction_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReqResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReqResult_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_datamsg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_datamsg_2eproto() {
  protobuf_AddDesc_datamsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "datamsg.proto");
  GOOGLE_CHECK(file != NULL);
  ReqAction_descriptor_ = file->message_type(0);
  static const int ReqAction_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqAction, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqAction, name_),
  };
  ReqAction_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReqAction_descriptor_,
      ReqAction::default_instance_,
      ReqAction_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReqAction),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqAction, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqAction, _is_default_instance_));
  ReqResult_descriptor_ = file->message_type(1);
  static const int ReqResult_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqResult, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqResult, msg_),
  };
  ReqResult_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReqResult_descriptor_,
      ReqResult::default_instance_,
      ReqResult_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReqResult),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqResult, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqResult, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_datamsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReqAction_descriptor_, &ReqAction::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReqResult_descriptor_, &ReqResult::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_datamsg_2eproto() {
  delete ReqAction::default_instance_;
  delete ReqAction_reflection_;
  delete ReqResult::default_instance_;
  delete ReqResult_reflection_;
}

void protobuf_AddDesc_datamsg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_datamsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rdatamsg.proto\022\006mqdemo\"\'\n\tReqAction\022\014\n\004"
    "type\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"&\n\tReqResult\022\014\n"
    "\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\tb\006proto3", 112);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datamsg.proto", &protobuf_RegisterTypes);
  ReqAction::default_instance_ = new ReqAction();
  ReqResult::default_instance_ = new ReqResult();
  ReqAction::default_instance_->InitAsDefaultInstance();
  ReqResult::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_datamsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_datamsg_2eproto {
  StaticDescriptorInitializer_datamsg_2eproto() {
    protobuf_AddDesc_datamsg_2eproto();
  }
} static_descriptor_initializer_datamsg_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqAction::kTypeFieldNumber;
const int ReqAction::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqAction::ReqAction()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mqdemo.ReqAction)
}

void ReqAction::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReqAction::ReqAction(const ReqAction& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mqdemo.ReqAction)
}

void ReqAction::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReqAction::~ReqAction() {
  // @@protoc_insertion_point(destructor:mqdemo.ReqAction)
  SharedDtor();
}

void ReqAction::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ReqAction::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqAction::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReqAction_descriptor_;
}

const ReqAction& ReqAction::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datamsg_2eproto();
  return *default_instance_;
}

ReqAction* ReqAction::default_instance_ = NULL;

ReqAction* ReqAction::New(::google::protobuf::Arena* arena) const {
  ReqAction* n = new ReqAction;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqAction::Clear() {
// @@protoc_insertion_point(message_clear_start:mqdemo.ReqAction)
  type_ = 0;
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ReqAction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mqdemo.ReqAction)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mqdemo.ReqAction.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mqdemo.ReqAction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mqdemo.ReqAction)
  return false;
#undef DO_
}

void ReqAction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mqdemo.ReqAction)
  // optional int32 type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mqdemo.ReqAction.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:mqdemo.ReqAction)
}

::google::protobuf::uint8* ReqAction::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mqdemo.ReqAction)
  // optional int32 type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mqdemo.ReqAction.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:mqdemo.ReqAction)
  return target;
}

int ReqAction::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:mqdemo.ReqAction)
  int total_size = 0;

  // optional int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqAction::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mqdemo.ReqAction)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReqAction* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqAction>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mqdemo.ReqAction)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mqdemo.ReqAction)
    MergeFrom(*source);
  }
}

void ReqAction::MergeFrom(const ReqAction& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mqdemo.ReqAction)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void ReqAction::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mqdemo.ReqAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqAction::CopyFrom(const ReqAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqdemo.ReqAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqAction::IsInitialized() const {

  return true;
}

void ReqAction::Swap(ReqAction* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqAction::InternalSwap(ReqAction* other) {
  std::swap(type_, other->type_);
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqAction::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReqAction_descriptor_;
  metadata.reflection = ReqAction_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqAction

// optional int32 type = 1;
void ReqAction::clear_type() {
  type_ = 0;
}
 ::google::protobuf::int32 ReqAction::type() const {
  // @@protoc_insertion_point(field_get:mqdemo.ReqAction.type)
  return type_;
}
 void ReqAction::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:mqdemo.ReqAction.type)
}

// optional string name = 2;
void ReqAction::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReqAction::name() const {
  // @@protoc_insertion_point(field_get:mqdemo.ReqAction.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReqAction::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mqdemo.ReqAction.name)
}
 void ReqAction::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mqdemo.ReqAction.name)
}
 void ReqAction::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mqdemo.ReqAction.name)
}
 ::std::string* ReqAction::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mqdemo.ReqAction.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReqAction::release_name() {
  // @@protoc_insertion_point(field_release:mqdemo.ReqAction.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReqAction::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mqdemo.ReqAction.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqResult::kCodeFieldNumber;
const int ReqResult::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqResult::ReqResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mqdemo.ReqResult)
}

void ReqResult::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReqResult::ReqResult(const ReqResult& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mqdemo.ReqResult)
}

void ReqResult::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  code_ = 0;
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReqResult::~ReqResult() {
  // @@protoc_insertion_point(destructor:mqdemo.ReqResult)
  SharedDtor();
}

void ReqResult::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ReqResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReqResult_descriptor_;
}

const ReqResult& ReqResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datamsg_2eproto();
  return *default_instance_;
}

ReqResult* ReqResult::default_instance_ = NULL;

ReqResult* ReqResult::New(::google::protobuf::Arena* arena) const {
  ReqResult* n = new ReqResult;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqResult::Clear() {
// @@protoc_insertion_point(message_clear_start:mqdemo.ReqResult)
  code_ = 0;
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ReqResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mqdemo.ReqResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 code = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_msg;
        break;
      }

      // optional string msg = 2;
      case 2: {
        if (tag == 18) {
         parse_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mqdemo.ReqResult.msg"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mqdemo.ReqResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mqdemo.ReqResult)
  return false;
#undef DO_
}

void ReqResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mqdemo.ReqResult)
  // optional int32 code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // optional string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mqdemo.ReqResult.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msg(), output);
  }

  // @@protoc_insertion_point(serialize_end:mqdemo.ReqResult)
}

::google::protobuf::uint8* ReqResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mqdemo.ReqResult)
  // optional int32 code = 1;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // optional string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mqdemo.ReqResult.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msg(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:mqdemo.ReqResult)
  return target;
}

int ReqResult::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:mqdemo.ReqResult)
  int total_size = 0;

  // optional int32 code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }

  // optional string msg = 2;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mqdemo.ReqResult)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReqResult* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mqdemo.ReqResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mqdemo.ReqResult)
    MergeFrom(*source);
  }
}

void ReqResult::MergeFrom(const ReqResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mqdemo.ReqResult)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
}

void ReqResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mqdemo.ReqResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqResult::CopyFrom(const ReqResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mqdemo.ReqResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqResult::IsInitialized() const {

  return true;
}

void ReqResult::Swap(ReqResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqResult::InternalSwap(ReqResult* other) {
  std::swap(code_, other->code_);
  msg_.Swap(&other->msg_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReqResult_descriptor_;
  metadata.reflection = ReqResult_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqResult

// optional int32 code = 1;
void ReqResult::clear_code() {
  code_ = 0;
}
 ::google::protobuf::int32 ReqResult::code() const {
  // @@protoc_insertion_point(field_get:mqdemo.ReqResult.code)
  return code_;
}
 void ReqResult::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:mqdemo.ReqResult.code)
}

// optional string msg = 2;
void ReqResult::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReqResult::msg() const {
  // @@protoc_insertion_point(field_get:mqdemo.ReqResult.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReqResult::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mqdemo.ReqResult.msg)
}
 void ReqResult::set_msg(const char* value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mqdemo.ReqResult.msg)
}
 void ReqResult::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mqdemo.ReqResult.msg)
}
 ::std::string* ReqResult::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:mqdemo.ReqResult.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReqResult::release_msg() {
  // @@protoc_insertion_point(field_release:mqdemo.ReqResult.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReqResult::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:mqdemo.ReqResult.msg)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace mqdemo

// @@protoc_insertion_point(global_scope)
