# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mymsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mymsg.proto',
  package='mydemo',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmymsg.proto\x12\x06mydemo\"7\n\x06ReqMsg\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x1f\n\x05ntype\x18\x02 \x01(\x0e\x32\x10.mydemo.NameType*.\n\x08NameType\x12\t\n\x05\x45MAIL\x10\x00\x12\t\n\x05PHONE\x10\x01\x12\x0c\n\x08USERNAME\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_NAMETYPE = _descriptor.EnumDescriptor(
  name='NameType',
  full_name='mydemo.NameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USERNAME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=80,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_NAMETYPE)

NameType = enum_type_wrapper.EnumTypeWrapper(_NAMETYPE)
EMAIL = 0
PHONE = 1
USERNAME = 2



_REQMSG = _descriptor.Descriptor(
  name='ReqMsg',
  full_name='mydemo.ReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mydemo.ReqMsg.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ntype', full_name='mydemo.ReqMsg.ntype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=78,
)

_REQMSG.fields_by_name['ntype'].enum_type = _NAMETYPE
DESCRIPTOR.message_types_by_name['ReqMsg'] = _REQMSG
DESCRIPTOR.enum_types_by_name['NameType'] = _NAMETYPE

ReqMsg = _reflection.GeneratedProtocolMessageType('ReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _REQMSG,
  __module__ = 'mymsg_pb2'
  # @@protoc_insertion_point(class_scope:mydemo.ReqMsg)
  ))
_sym_db.RegisterMessage(ReqMsg)


# @@protoc_insertion_point(module_scope)
